title: CaesarSec
author: Lyle Irvine
email: lyleirvine72@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  A personal blog focusing on technology and cybersecurity, with the chance of veering off into self-improvement and life.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: CaesarSec
  tagline: Technology, Cybersecurity and Life
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  navigation:
  - title: Home
    url: "/"
  - title: Post List
    url: "/posts"
  - title: About
    url: "/about"
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: caesarsec_
    github:  caesar-sec
    email: lyleirvine72@gmail.com
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
#theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed